### ISSUE TITLE
Update Hearthstone GLOBAL strings for Boomsday

### ISSUE THREAD

**Issue by beheh** [HearthSim/hsreplaynet-i18n#1]
We're currently missing the Boomsday strings, or at least `GLOBAL_KEYWORD_MODULAR`.

**Comment by jleclanche** [comment]
https://github.com/HearthSim/hsreplaynet-i18n/blob/master/hearthstone/en/global.json#L436 ...?

**Comment by beheh** [comment]
Oh, I was working against an outdated copy. My bad.
